//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB7.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LAB7.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про програ&amp;му....
        /// </summary>
        internal static string AboutUA {
            get {
                return ResourceManager.GetString("AboutUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Кількість символів: &quot; + richTextBox1.Text.Length.ToString().
        /// </summary>
        internal static string AmountUA {
            get {
                return ResourceManager.GetString("AmountUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К&amp;аскад.
        /// </summary>
        internal static string CascadeUA {
            get {
                return ResourceManager.GetString("CascadeUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ко&amp;лір.
        /// </summary>
        internal static string ColorUA {
            get {
                return ResourceManager.GetString("ColorUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Копіювати.
        /// </summary>
        internal static string CopyUA {
            get {
                return ResourceManager.GetString("CopyUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви&amp;різати.
        /// </summary>
        internal static string cutUA {
            get {
                return ResourceManager.GetString("cutUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви&amp;далити.
        /// </summary>
        internal static string DeleteUA {
            get {
                return ResourceManager.GetString("DeleteUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Редагувати.
        /// </summary>
        internal static string editUA {
            get {
                return ResourceManager.GetString("editUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Знайти.
        /// </summary>
        internal static string FindUA {
            get {
                return ResourceManager.GetString("FindUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Шрифт.
        /// </summary>
        internal static string FontUA {
            get {
                return ResourceManager.GetString("FontUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф&amp;ормат.
        /// </summary>
        internal static string formatUA {
            get {
                return ResourceManager.GetString("formatUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По &amp;горизонталі.
        /// </summary>
        internal static string HorizonUA {
            get {
                return ResourceManager.GetString("HorizonUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В&amp;ийти.
        /// </summary>
        internal static string mnuExitUA {
            get {
                return ResourceManager.GetString("mnuExitUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Файл.
        /// </summary>
        internal static string mnuFileUA {
            get {
                return ResourceManager.GetString("mnuFileUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Новий.
        /// </summary>
        internal static string mnuNewUA {
            get {
                return ResourceManager.GetString("mnuNewUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Відкрити.
        /// </summary>
        internal static string mnuOpenUA {
            get {
                return ResourceManager.GetString("mnuOpenUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти &amp;Як.
        /// </summary>
        internal static string mnuSaveAsUA {
            get {
                return ResourceManager.GetString("mnuSaveAsUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;Зберегти.
        /// </summary>
        internal static string mnuSaveUA {
            get {
                return ResourceManager.GetString("mnuSaveUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В&amp;ставити.
        /// </summary>
        internal static string PasteUA {
            get {
                return ResourceManager.GetString("PasteUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви&amp;брати Все.
        /// </summary>
        internal static string SelectAllUA {
            get {
                return ResourceManager.GetString("SelectAllUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &amp;По вертикалі.
        /// </summary>
        internal static string VertUA {
            get {
                return ResourceManager.GetString("VertUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В&amp;ікно.
        /// </summary>
        internal static string windowUA {
            get {
                return ResourceManager.GetString("windowUA", resourceCulture);
            }
        }
    }
}
